### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by lentitude** [shangjingbo1226/AutoPhrase#34]
when I clone the project and run the auto_phrase.sh directly , some exception occured:

===Saving Model and Results===
cp: cannot stat 'tmp/segmentation.model': No such file or directory
===Generating Output===
java.io.FileNotFoundException: tmp/final_quality_multi-words.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at Tokenizer.tokenizeText(Tokenizer.java:705)
	at Tokenizer.main(Tokenizer.java:856)
java.io.FileNotFoundException: tmp/final_quality_unigrams.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at Tokenizer.tokenizeText(Tokenizer.java:705)
	at Tokenizer.main(Tokenizer.java:856)
java.io.FileNotFoundException: tmp/final_quality_salient.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at Tokenizer.tokenizeText(Tokenizer.java:705)
	at Tokenizer.main(Tokenizer.java:856)

**Comment by lentitude** [comment]
lentitude@ubuntu:~$ java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
lentitude@ubuntu:~$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

This is my computer environment ? I don't know how to cause this problem., When I creat the file which can't be found by myself , the program make successful , but i can't sure whether the result is true

**Comment by shangjingbo1226** [comment]
I will check it soon. Thanks for letting me know.

**Comment by lentitude** [comment]
The question has been solved when i install the VM and environment again,although i don't know what cause the question before.Thanks for you reply

**Comment by Yevgnen** [comment]
Got a similar problem on my ubuntu 18.04

```
auto_phrase.sh: 45: [: -eq: unexpected operator
auto_phrase.sh: 54: [: data/EN/DBLP.5K.txt: unexpected operator
===Tokenization===
-ne Current step: Tokenizing input file...
2.05user 0.06system 0:00.61elapsed 344%CPU (0avgtext+0avgdata 147804maxresident)k
0inputs+2992outputs (0major+34970minor)pagefaults 0swaps
-ne Detected Language: EN

-ne Current step: Tokenizing stopword file...
-ne Current step: Tokenizing wikipedia phrases...

auto_phrase.sh: 93: auto_phrase.sh: [[: not found
-ne No provided expert labels.

auto_phrase.sh: 100: [: EN: unexpected operator
===AutoPhrasing===
=== Current Settings ===
Iterations = 2
Minimum Support Threshold = 10
Maximum Length Threshold = 6
POS-Tagging Mode Enabled
Number of threads = 10
Labeling Method = DPDN
	Auto labels from knowledge bases
	Max Positive Samples = -1
=======
Loading data...
# of total tokens = 123017
max word token id = 9893
[Warning] failed to open tmp/pos_tags_tokenized_train.txt under parameters = r
Command terminated by signal 11
0.00user 0.00system 0:00.09elapsed 8%CPU (0avgtext+0avgdata 4272maxresident)k
0inputs+0outputs (0major+190minor)pagefaults 0swaps
===Saving Model and Results===
cp: cannot stat 'tmp/segmentation.model': No such file or directory
===Generating Output===
java.io.FileNotFoundException: tmp/final_quality_multi-words.txt (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at Tokenizer.tokenizeText(Tokenizer.java:713)
	at Tokenizer.main(Tokenizer.java:864)
java.io.FileNotFoundException: tmp/final_quality_unigrams.txt (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at Tokenizer.tokenizeText(Tokenizer.java:713)
	at Tokenizer.main(Tokenizer.java:864)
java.io.FileNotFoundException: tmp/final_quality_salient.txt (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at Tokenizer.tokenizeText(Tokenizer.java:713)
	at Tokenizer.main(Tokenizer.java:864)
```

`uname -a`:
```
Linux user-Shangqi-V4270 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
