### ISSUE TITLE
run auto_phrase.sh, and throw exception tmp/final_quality_multi-words.txt (No such file or directory)

### ISSUE THREAD

**Issue by sky94520** [shangjingbo1226/AutoPhrase#88]
the detail is:
```
===Saving Model and Results===
cp: cannot stat 'tmp/segmentation.model': No such file or directory
===Generating Output===
java.io.FileNotFoundException: tmp/final_quality_multi-words.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at Tokenizer.tokenizeText(Tokenizer.java:713)
	at Tokenizer.main(Tokenizer.java:864)
java.io.FileNotFoundException: tmp/final_quality_unigrams.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at Tokenizer.tokenizeText(Tokenizer.java:713)
	at Tokenizer.main(Tokenizer.java:864)
java.io.FileNotFoundException: tmp/final_quality_salient.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at Tokenizer.tokenizeText(Tokenizer.java:713)
	at Tokenizer.main(Tokenizer.java:864)
```
I run the shell script with default parameters,  could you please tell me what to do next?
thanks!

**Comment by sky94520** [comment]
it is my fault, the RAM of my computer is not enough.
